print("##########################################################")
print("#                                                        #")
print("#                     \||/                               #")
print("#                     |  @___oo                          #")
print("#           /\  /\   / (__,,,,|                          #")
print("#          ) /^\) ^\/ _)           Annoying program      #")
print("#          )   /^\/   _)     CoDeD By: Lev Shapiro       #")
print("#          )   _ /  / _)                                 #")
print("#      /\  )/\/ ||  | )_)                                #")
print("#     <  >      |(,,) )__)                               #")
print("#      ||      /    \)___)\                              #")
print("#      | \____(      )___) )___                          #")
print("#      \______(_______;;; __;;;                          #")
print("#                                                        #")
print("##########################################################")
print("\n")
print("Options:")
print("1. I t' s _ _ _ e x a m p l e ")
print("2. I T S E X A M P L E")
check = input("Enter number that you want to apply: ")
if check == '1':
    hello = input('Enter here the sentence: ')
    b = hello.replace(' ', '___')
    c = " ".join(b)
    print(c)
elif check == '2':
    result = input('Enter here the sentence: ')
    print(result.upper())
else:
    print("Are you idiot? You don't know what word number, means?!")
